---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/nareshgnT/pcf-attendee-service-code.git
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.run-01.haas-66.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: nnagarajan-pal
    space: sandbox
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

